# tell docker what version of the docker-compose.yml we're using
version: '3'

# define the network
networks:
  web-network:

services:
  docker-php-cli:
    # define the directory where the build should happened,
    # i.e. where the Dockerfile of the service is located
    # all paths are relative to the location of docker-compose.yml
    build:
      context: ./php-cli/
    tty: true
    # mount the app directory of the host to /var/www in the container
    volumes:
      - ../:/var/www
      - ~/.bash_history:/root/.bash_history
    # connect to the network
    networks:
      - web-network

  docker-nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ../:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-network

  docker-php-fpm:
    build:
      context: ./php-fpm
    tty: true
    volumes:
      - ../:/var/www
    networks:
      - web-network

  docker-db:
    image: mysql:5.6.46
    restart: always
    environment:
      MYSQL_DATABASE: 'eactivos'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '6666:3306'
    volumes:
      - ../app/docker-volume/mysql:/var/lib/mysql
    networks:
      - web-network

  docker-encore:
    build:
      context: ./encore
    volumes:
      - ../:/var/www
    ports:
      - "${DEV_SERVER_PORT:-8088}:8088"
    command: ["yarn", "dev-server", "--host=0.0.0.0"]
    networks:
      - web-network
