# tell docker what version of the docker-compose.yml we're using
version: '3'

# define the network
networks:
  web-network:

# start the services section
services:
  # define the name of our service
  # corresponds to the "--name" parameter
  docker-php-cli:
    # define the directory where the build should happened,
    # i.e. where the Dockerfile of the service is located
    # all paths are relative to the location of docker-compose.yml
    build:
      context: ./php-cli/
      dockerfile: Dockerfile

    # reserve a tty - otherwise the container shuts down immediately
    # corresponds to the "-i" flag
    tty: true
    # mount the app directory of the host to /var/www in the container
    # corresponds to the "-v" option
    volumes:
      - ../:/var/www
      - ~/.bash_history:/root/.bash_history
    # connect to the network
    # corresponds to the "--network" option
    networks:
      - web-network

  docker-nginx:
    build:
      context: ./nginx
    # defines the port mapping
    # corresponds to the "-p" flag
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ../:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-network

  docker-php-fpm:
    build:
      context: ./php-fpm
    tty: true
    volumes:
      - ../:/var/www
    networks:
      - web-network

  docker-db:
    image: mysql:5.6.46
    restart: always
    environment:
      MYSQL_DATABASE: 'eactivos'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '6666:3306'
    # Where our data will be persisted
    volumes:
      - ../app/docker-volume/mysql:/var/lib/mysql
    networks:
      - web-network

  docker-nodejs:
    build:
      context: ./nodejs/
      dockerfile: Dockerfile

    volumes:
      - ../:/var/www

    networks:
      - web-network
