services:
  app.auction.manager:
    class: App\Manager\AuctionManager
    public: true
    arguments: [App\Entity\Auction, "@doctrine.orm.entity_manager"]
    tags:
      - { name: 'app.auction.manager' }

  app.lots.manager:
    class: App\Manager\LotsManager
    public: true
    arguments: [App\Entity\Lots, "@doctrine.orm.entity_manager"]
    tags:
      - { name: 'app.lots.manager' }

  app.products.manager:
    class: App\Manager\ProductsManager
    public: true
    arguments: [App\Entity\Products, "@doctrine.orm.entity_manager"]
    tags:
      - { name: 'app.products.manager' }
